### PR TITLE
[BUGFIX] Workaround for problem with compatibility6 #44

### PR DESCRIPTION
**Pull request by sypets**

### CODE REVIEW

**Comment by sypets** [comment]
This PR can no longer be applied 'cause The file Classes/Hooks/Tca/AddFilesToSelector.php no longer exists in master (see merge conflicts). Probably the problem still remains with Classes/Hooks/FormEngine/LegacyPluginSelector.php. Needs to be checked and another commit added or new PR.

**Comment by sypets** [comment]
It makes no sense to merge this PR because of substantial changes in the codebase.

The following code should be changed now with the newest version: https://github.com/FriendsOfTYPO3/tt_address/blob/99c52e1b193faa781d8998241a0e42c887296cdc/Classes/Hooks/FormEngine/LegacyPluginSelector.php#L87

$params['flexParentDatabaseRow']['pid'] will be unset if compatibility6 is activated.

This will not be necessary once compatibility6 is fixed, see https://github.com/FriendsOfTYPO3/compatibility6/pull/17

**Comment by bmack** [comment]
Should be created against 3.3 branch, can you do that? I will then release a new version.

**Comment by sypets** [comment]
Does anyone know how to change the **base** and **target** branch for a pull request? 

I don't know how to do that and don't know if it's even possible. I found an issue for github for changing the target branch (https://github.com/isaacs/github/issues/18) which is apparently "implemented".

If I don't figure out how to do this, I'll open up a new PR for this. Hang on ...

**Comment by sypets** [comment]
I created a new PR now for branch 3.3: https://github.com/FriendsOfTYPO3/tt_address/pull/46

However the problem also exists in master branch (4.0.0).

**Pull request closed without merging**
