### PR TITLE
[FEATURE] Add GoogleMaps location selection support

### PR DESCRIPTION
**Pull request by liayn**
The user is not forced to type the coordinates manually,
but can use the interactive map to select the location of choice.

### CODE REVIEW

**Comment by liayn** [comment]
-1
I forgot to add a label.

**Comment by liayn** [comment]
Now with the label.

**Comment by liayn** [comment]
@bmack ping

**Comment by SvenJuergens** [comment]
hi,
testet this on a fresh (local) TYPO3 7.6.12 installation
When i save the tt_address Record i got the error

> 1: These fields of record 2 in table "tt_address" have not been saved correctly: latitude! The values might have changed due to type casting of the database.

**Comment by BastianBalthasarBux** [comment]
Hi Sven,
Thanks for your testing and feedback!
We are currently working on a custom evaluation (as it is not possible to do a valid evaluation with the methods available by default), and adding a wizard based on OSM.
Furthermore there were recently changes on our master, which happend after this fork and pull-request, to optimize these things.
So please stand by and show some patience. ;)

**Comment by liayn** [comment]
@SvenJuergens This PR is fully outdated and does not match latest tt_address anymore as Bastian pointed out. Moreover, if a solution with OSM is scheduled, this example implementation is subject to be abandoned I suppose, still it is an example how one can implement renderTypes for FormEngine.

**Comment by SvenJuergens** [comment]
@liayn that's the way i found this pull request, i searched for examples and documentation for FormEngine and use of own renderTypes ;)

**Comment by BastianBalthasarBux** [comment]
and that's why I did not close this PR till now. ;)

**Pull request closed without merging**
