### PR TITLE
[TASK] Add localization for records

### PR DESCRIPTION
**Pull request by Mruts**
I want to resolve Issue #13 (Missing function: Localize records)

### CODE REVIEW

**Comment by BastianBalthasarBux** [comment]
Thanks for contribution. ATM I have some work in the pipe too, I will test your PR the next few days. Looks promising by reading.

**Comment by Mruts** [comment]
Your welcome - no problem ;)

**Comment by Mruts** [comment]
Take care if you merge pi1/class.tx_ttaddress_pi1.php, because I implemented the feature in tt_address 3.0.3. It could overwrite changes made by commits in the past (between 3.0.3 and current master).

**Comment by BastianBalthasarBux** [comment]
Thanks for the info.
But we plan to mark pi1 as obsolete anyway, and there is an extbasecontroller in the pipe (already on my local machine in progress ...).
That's why I need to multiple-check your changes anyway, as I think it should work with extbase too from the very beginning.
But I can't do this in that week ..., I plan this for the end of next week, around 9.-10. of march.

**Comment by BastianBalthasarBux** [comment]
You are invited to be vexatious if I am not back to you till 15th of march. ;)

**Comment by BastianBalthasarBux** [comment]
It's April now, and I managed to bake a fork with a couple of changes, including transaltion-feature for the backend.
Implementation in Frontend will be done along with extbase controller and fluid templates.
Feel free to test the current state (on your own risk pls): https://github.com/BastianBalthasarBux/tt_address (I used to implement this on a 7.6 branch, not yet tested with 8.7!)

**Comment by BastianBalthasarBux** [comment]
I will close this pullrequest now because of following reasons:
1. There will be a solution in the next version, already partly implemented in my own fork
2. The code of this pullrequest is not only violating CGL partly but also erroneous and cannot be merged automatically therefore.

**Comment by ogrosko** [comment]
@BastianBalthasarBux when it's planed to release stable version to TER with localization functionality?
Now I'm using your [fork](https://github.com/BastianBalthasarBux/tt_address), is it stable enough to use in production?

**Comment by BastianBalthasarBux** [comment]
Hi, I am not sure when this will happen, although it is planned for sure! I will talk/slack with @bmack the next few days, how and when we will proceed now.
Stability: I consider my fork as almost stable, although there seems to be a problem with FE and the sorting (querygenerator). Look at the issue at my fork. I will do more tests these days, also on v8 (!!), and there will arrive some of the features which are planned now for a long time in the next couple of weeks.
I am also pretty sure that there won't be breaking changes when merging to master, the Domain (and DB) is pretty much the same anyway but also the plugin-flexform for extbase FE should not be breaking-changed anymore, although I cannot guarantee for that. ;)

**Comment by ogrosko** [comment]
Great thank you for info. ;)

**Pull request closed without merging**
